FROM ghcr.io/graalvm/graalvm-ce:latest as builder
COPY ./ /app
WORKDIR /app
RUN ./mvnw -DskipTests package && \
    gu install native-image && \
    cd target && \
    native-image -H:Name=spring-native-demo -cp classes/META-INF:spring-native-demo-0.0.1-SNAPSHOT.jar

FROM debian:latest
COPY --from=builder /app/target/spring-native-demo /app/spring-native-demo
EXPOSE 8080:8080
WORKDIR /app
CMD ["./spring-native-demo"]
