FROM openjdk AS builder-jar
COPY ./ /app
WORKDIR /app
RUN ./mvnw -DskipTests package

FROM ubuntu:latest AS builder-native
VOLUME /var/run/docker.sock
VOLUME /var/run/docker-cli.sock
COPY --from=builder-jar /app/target/spring-native-demo-0.0.1-SNAPSHOT.jar /app/spring-native-demo-0.0.1-SNAPSHOT.jar
WORKDIR /app
RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:cncf-buildpacks/pack-cli && \
    apt install -y pack-cli && \
    pack build --builder paketobuildpacks/builder:tiny \
        --path /app/spring-native-demo-0.0.1-SNAPSHOT.jar --env 'BP_NATIVE_IMAGE=true' spring-native-demo


FROM debian:latest
COPY --from=builder-native /app/target/spring-native-demo /app/spring-native-demo
EXPOSE 8080:8080
WORKDIR /app
CMD ["./spring-native-demo"]
